export default function Privacy() {
  const effectiveDate = "July 7, 2026";

  return (
    <main style={{ background: "#f7f5f0", minHeight: "100vh", paddingBottom: "60px" }}>
      <div style={{ maxWidth: "760px", margin: "0 auto", padding: "0 16px" }}>

        <div className="rm-section-header-blue" style={{ marginTop: "20px" }}>
          [ PRIVACY POLICY ]
        </div>

        <div className="rm-card" style={{ padding: "24px 28px", fontFamily: "Georgia, 'Times New Roman', serif", lineHeight: "1.7", color: "#222" }}>

          <p style={{ fontFamily: "Courier New, monospace", fontSize: "11px", color: "#888", marginBottom: "20px", borderBottom: "1px solid #ddd", paddingBottom: "12px" }}>
            Effective Date: {effectiveDate} &nbsp;|&nbsp; Operator: Petite Hache Labs, LLC &nbsp;|&nbsp; Contact: <a href="mailto:notices@rhymemath.com" style={{ color: "#1a3a7a" }}>notices@rhymemath.com</a>
          </p>

          <p style={{ fontSize: "14px", marginBottom: "20px" }}>
            This Privacy Policy describes how Petite Hache Labs, LLC ("we," "us," or "our") collects, uses, and handles information in connection with RhymeMath, accessible at rhymemath.com (the "Service"). By using the Service, you agree to the practices described in this policy.
          </p>

          {/* Section 1 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            1. Who We Are
          </h2>
          <p style={{ fontSize: "14px", marginBottom: "12px" }}>
            RhymeMath is operated by Petite Hache Labs, LLC, a company organized under the laws of New York. For any privacy-related questions or requests, contact us at <a href="mailto:notices@rhymemath.com" style={{ color: "#1a3a7a" }}>notices@rhymemath.com</a>.
          </p>

          {/* Section 2 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            2. What We Collect
          </h2>
          <p style={{ fontSize: "14px", marginBottom: "8px" }}>We collect the following information when you use the Service:</p>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "13px", marginBottom: "16px" }}>
            <thead>
              <tr style={{ background: "#1a3a7a" }}>
                <th style={{ padding: "7px 10px", textAlign: "left", color: "#aaccff", fontFamily: "Arial, sans-serif", fontSize: "11px" }}>Data Type</th>
                <th style={{ padding: "7px 10px", textAlign: "left", color: "#aaccff", fontFamily: "Arial, sans-serif", fontSize: "11px" }}>Description</th>
                <th style={{ padding: "7px 10px", textAlign: "left", color: "#aaccff", fontFamily: "Arial, sans-serif", fontSize: "11px" }}>Purpose</th>
              </tr>
            </thead>
            <tbody>
              {[
                ["Verse text", "Rap lyrics you submit for analysis or comparison.", "Core service delivery; scoring and leaderboard population."],
                ["Artist and song names", "Names you enter alongside submitted verses.", "Labeling analyses; building the rapper database and leaderboards."],
                ["Analysis results", "Scores generated by our engine across flow, wordplay, storytelling, rhyming, and punchlines.", "Displaying results; building the leaderboard and rapper database."],
                ["Server logs / IP addresses", "Standard web server logs captured automatically on each request.", "Security, abuse prevention, and operational diagnostics. Purged after 90 days."],
              ].map(([type, desc, purpose], i) => (
                <tr key={i} style={{ background: i % 2 === 0 ? "#fff" : "#f5f3ef", borderBottom: "1px solid #e0ddd8" }}>
                  <td style={{ padding: "7px 10px", fontWeight: "bold", verticalAlign: "top" }}>{type}</td>
                  <td style={{ padding: "7px 10px", verticalAlign: "top" }}>{desc}</td>
                  <td style={{ padding: "7px 10px", verticalAlign: "top", color: "#555" }}>{purpose}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <p style={{ fontSize: "13px", color: "#555", marginBottom: "12px" }}>
            <strong>No account data.</strong> RhymeMath has no login system. We do not collect names, email addresses, passwords, or payment information.
          </p>
          <p style={{ fontSize: "13px", color: "#555", marginBottom: "12px" }}>
            <strong>Cookies.</strong> We do not currently place analytics or advertising cookies on your device. If we add analytics or advertising tools in the future, we will update this policy, implement a consent banner, and provide an opt-out mechanism before any such tools are activated.
          </p>

          {/* Section 3 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            3. How We Use Your Information
          </h2>
          <ul style={{ fontSize: "14px", paddingLeft: "20px", marginBottom: "12px" }}>
            {[
              "To provide, operate, and improve the Service.",
              "To generate and display verse analysis scores and comparison results.",
              "To populate leaderboards and the rapper database with aggregated, pseudonymous data.",
              "To detect and prevent abuse, fraud, or unauthorized use.",
              "To maintain and improve the security and performance of our systems.",
            ].map((item, i) => (
              <li key={i} style={{ marginBottom: "6px" }}>{item}</li>
            ))}
          </ul>
          <p style={{ fontSize: "14px", marginBottom: "12px" }}>
            We do not use your submitted verse text to train machine learning models, and we do not sell personally identifying information to third parties.
          </p>
          <p style={{ fontSize: "14px", marginBottom: "12px" }}>
            Aggregated, anonymized datasets (for example, aggregate scoring statistics across all analyzed verses) may be used or licensed commercially as a proprietary dataset. No IP address, device identifier, or other individual identifier is included in or re-linkable to any such dataset.
          </p>

          {/* Section 4 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            4. Fair Use and Analytical Purpose
          </h2>
          <p style={{ fontSize: "14px", marginBottom: "12px" }}>
            RhymeMath is an analytical platform. Verse text submitted by users is processed algorithmically to generate scores and comparisons. This analytical and transformative use is intended to qualify as fair use under 17 U.S.C. Section 107. We do not reproduce, republish, or distribute submitted lyrics for entertainment or commercial exploitation.
          </p>

          {/* Section 5 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            5. Legal Basis for Processing (GDPR)
          </h2>
          <p style={{ fontSize: "14px", marginBottom: "8px" }}>
            For users in the European Economic Area (EEA) or United Kingdom, we rely on the following legal bases under GDPR:
          </p>
          <ul style={{ fontSize: "14px", paddingLeft: "20px", marginBottom: "12px" }}>
            <li style={{ marginBottom: "6px" }}><strong>Legitimate interests</strong> (Article 6(1)(f)) for core service delivery, security, and operational logging.</li>
            <li style={{ marginBottom: "6px" }}><strong>Consent</strong> (Article 6(1)(a)) for any future analytics or advertising cookies, which will not be placed until affirmative opt-in consent is obtained.</li>
          </ul>

          {/* Section 6 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            6. Data Retention
          </h2>
          <ul style={{ fontSize: "14px", paddingLeft: "20px", marginBottom: "12px" }}>
            <li style={{ marginBottom: "6px" }}><strong>Verse text and analysis results:</strong> Retained indefinitely as part of our proprietary dataset, unless a deletion request is submitted.</li>
            <li style={{ marginBottom: "6px" }}><strong>Server logs and IP addresses:</strong> Purged after 90 days.</li>
          </ul>

          {/* Section 7 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            7. Your Rights
          </h2>
          <p style={{ fontSize: "14px", marginBottom: "8px" }}>Depending on where you are located, you may have the following rights:</p>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "13px", marginBottom: "16px" }}>
            <thead>
              <tr style={{ background: "#1a3a7a" }}>
                <th style={{ padding: "7px 10px", textAlign: "left", color: "#aaccff", fontFamily: "Arial, sans-serif", fontSize: "11px" }}>Right</th>
                <th style={{ padding: "7px 10px", textAlign: "left", color: "#aaccff", fontFamily: "Arial, sans-serif", fontSize: "11px" }}>GDPR (EEA/UK)</th>
                <th style={{ padding: "7px 10px", textAlign: "left", color: "#aaccff", fontFamily: "Arial, sans-serif", fontSize: "11px" }}>CCPA (California)</th>
              </tr>
            </thead>
            <tbody>
              {[
                ["Right to know / access", "Yes", "Yes"],
                ["Right to deletion", "Yes", "Yes"],
                ["Right to data portability", "Yes", "No"],
                ["Right to object to processing", "Yes", "No"],
                ["Right to opt out of sale/sharing", "N/A", "Yes"],
              ].map(([right, gdpr, ccpa], i) => (
                <tr key={i} style={{ background: i % 2 === 0 ? "#fff" : "#f5f3ef", borderBottom: "1px solid #e0ddd8" }}>
                  <td style={{ padding: "7px 10px", verticalAlign: "top" }}>{right}</td>
                  <td style={{ padding: "7px 10px", textAlign: "center", color: gdpr === "Yes" ? "#006600" : "#999" }}>{gdpr}</td>
                  <td style={{ padding: "7px 10px", textAlign: "center", color: ccpa === "Yes" ? "#006600" : "#999" }}>{ccpa}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <p style={{ fontSize: "14px", marginBottom: "12px" }}>
            To exercise any of these rights, contact us at <a href="mailto:notices@rhymemath.com" style={{ color: "#1a3a7a" }}>notices@rhymemath.com</a>. We will respond within 30 days (or 45 days where permitted by law). We do not currently sell personally identifying information, so no "Do Not Sell" opt-out is required at this time. If that changes, we will update this policy and provide a clear opt-out mechanism before any such activity begins.
          </p>

          {/* Section 8 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            8. Third Parties and Data Sharing
          </h2>
          <p style={{ fontSize: "14px", marginBottom: "8px" }}>We do not sell, rent, or trade your personal information. We may share information in the following limited circumstances:</p>
          <ul style={{ fontSize: "14px", paddingLeft: "20px", marginBottom: "12px" }}>
            <li style={{ marginBottom: "6px" }}><strong>Service providers:</strong> Infrastructure providers (such as Railway for hosting and PostgreSQL for database services) that process data on our behalf under confidentiality obligations.</li>
            <li style={{ marginBottom: "6px" }}><strong>Legal compliance:</strong> If required by law, court order, or to protect the rights, property, or safety of Petite Hache Labs, LLC or others.</li>
            <li style={{ marginBottom: "6px" }}><strong>Business transfer:</strong> In connection with a merger, acquisition, or sale of assets, subject to customary confidentiality protections.</li>
          </ul>

          {/* Section 9 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            9. Children
          </h2>
          <p style={{ fontSize: "14px", marginBottom: "12px" }}>
            The Service is not directed to children under 13, and we do not knowingly collect personal information from children under 13. If you believe we have inadvertently collected such information, contact us at <a href="mailto:notices@rhymemath.com" style={{ color: "#1a3a7a" }}>notices@rhymemath.com</a> and we will delete it promptly.
          </p>

          {/* Section 10 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            10. Security
          </h2>
          <p style={{ fontSize: "14px", marginBottom: "12px" }}>
            We implement commercially reasonable technical and organizational measures to protect information against unauthorized access, loss, or disclosure. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.
          </p>

          {/* Section 11 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            11. Changes to This Policy
          </h2>
          <p style={{ fontSize: "14px", marginBottom: "12px" }}>
            We may update this Privacy Policy from time to time. If we make material changes, we will update the Effective Date above and, where required by law, provide notice. Continued use of the Service after any update constitutes acceptance of the revised policy.
          </p>

          {/* Section 12 */}
          <h2 style={{ fontFamily: "Arial Black, Arial, sans-serif", fontSize: "13px", color: "#1a3a7a", textTransform: "uppercase", marginTop: "28px", marginBottom: "10px", borderBottom: "2px solid #1a3a7a", paddingBottom: "4px" }}>
            12. Contact
          </h2>
          <p style={{ fontSize: "14px", marginBottom: "4px" }}>
            For any privacy questions, requests, or complaints, contact:
          </p>
          <div style={{ fontFamily: "Courier New, monospace", fontSize: "12px", background: "#fff", border: "1px solid #ddd", padding: "12px 14px", marginTop: "8px" }}>
            <strong>Petite Hache Labs, LLC</strong><br />
            Operator of RhymeMath<br />
            <a href="mailto:notices@rhymemath.com" style={{ color: "#1a3a7a" }}>notices@rhymemath.com</a><br />
            Governing law: State of New York
          </div>

          <p style={{ fontFamily: "Courier New, monospace", fontSize: "10px", color: "#999", marginTop: "24px", borderTop: "1px solid #ddd", paddingTop: "12px" }}>
            This policy was last updated on {effectiveDate}. For questions about our Terms of Service, visit <a href="/#/terms" style={{ color: "#1a3a7a" }}>rhymemath.com/terms</a>.
          </p>

        </div>
      </div>
    </main>
  );
}
